DROP TABLE MESSAGES;
DROP TABLE CRAFTED_STATE;
DROP TABLE KEYWORDS;
DROP TABLE NETWORKS;
DROP TABLE CRAFTED_STATE;
DROP TABLE CUSTOMER_CONTACT;
DROP TABLE CONTACT;
DROP TABLE CUSTOMERS;
DROP TABLE CONTACT_TYPE;

CREATE TABLE CRAFTED_STATE (
	CRAFTED_STATE_ID VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(80),
	CREATED_TS TIMESTAMP NOT NULL,
	LAST_UPDATED_TS TIMESTAMP,
	CONSTRAINT PK_cs PRIMARY KEY (CRAFTED_STATE_ID)
);

CREATE TABLE CONTACT_TYPE(
	CONTACT_TYPE_ID VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(80),
	CREATED_TS TIMESTAMP NOT NULL,
	LAST_UPDATED_TS TIMESTAMP,
	CONSTRAINT PK_contTyp PRIMARY KEY (CONTACT_TYPE_ID)
);

CREATE TABLE CUSTOMERS(
	CUSTOMER_ID INT NOT NULL,
	CREATED_TS TIMESTAMP NOT NULL,
	LAST_UPDATED_TS TIMESTAMP,
	CONSTRAINT PK_cust PRIMARY KEY (CUSTOMER_ID)
);

CREATE TABLE CONTACT(
	CONTACT_ID INT NOT NULL,
	CONTACT_TYPE_ID VARCHAR(20) NOT NULL,
	INFO_STRING VARCHAR(200),
	CREATED_TS TIMESTAMP NOT NULL,
	LAST_UPDATED_TS TIMESTAMP,
	CONSTRAINT PK_cont PRIMARY KEY (CONTACT_ID),
	CONSTRAINT FK_cont_typ
     FOREIGN KEY (CONTACT_TYPE_ID)
     REFERENCES CONTACT_TYPE(CONTACT_TYPE_ID)
);

CREATE TABLE CUSTOMER_CONTACT(
	CUSTOMER_ID INT NOT NULL,
	CONTACT_ID INT NOT NULL,
	CREATED_TS TIMESTAMP NOT NULL,
	LAST_UPDATED_TS TIMESTAMP,
	CONSTRAINT PK_cust_cont PRIMARY KEY (CONTACT_ID,CUSTOMER_ID),
	CONSTRAINT FK_cc_cust
     FOREIGN KEY (CUSTOMER_ID)
     REFERENCES CUSTOMERS(CUSTOMER_ID),
    CONSTRAINT FK_cc_cont
     FOREIGN KEY (CONTACT_ID)
     REFERENCES CONTACT(CONTACT_ID)
);

CREATE TABLE NETWORKS(
	NETWORK_ID VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(80),
	CREATED_TS TIMESTAMP NOT NULL,
	LAST_UPDATED_TS TIMESTAMP,
	CONSTRAINT PK_net PRIMARY KEY (NETWORK_ID)
);

CREATE TABLE KEYWORDS(
	KEYWORD_ID INT NOT NULL,
	KEYWORD VARCHAR(50) NOT NULL,
	CUSTOMER_ID INT NOT NULL,
	CREATED_TS TIMESTAMP NOT NULL,
	LAST_UPDATED_TS TIMESTAMP,
	CONSTRAINT PK_kw PRIMARY KEY (KEYWORD_ID),
	CONSTRAINT FK_kw_cust
     FOREIGN KEY (CUSTOMER_ID)
     REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE MESSAGES(
     MESSAGE_ID INT NOT NULL,
     MESSAGE VARCHAR(1024),
     FROM_USER_ID VARCHAR(128),
     LANGUAGE VARCHAR(5),
     NETWORK_ID VARCHAR(20) NOT NULL,
     NETWORK_MESSAGE_DATE TIMESTAMP,
     MESSAGE_RECEIVED_DATE TIMESTAMP,
     CUSTOMER_ID INT NOT NULL,
     CRAFTED_STATE_ID VARCHAR(20) NOT NULL,
     CREATED_TS TIMESTAMP NOT NULL,
	 LAST_UPDATED_TS TIMESTAMP,
     CONSTRAINT PK_msg PRIMARY KEY (MESSAGE_ID),
     CONSTRAINT FK_msg_cs
     FOREIGN KEY (CRAFTED_STATE_ID)
     REFERENCES CRAFTED_STATE(CRAFTED_STATE_ID),
     CONSTRAINT FK_msg_cust
     FOREIGN KEY (CUSTOMER_ID)
     REFERENCES CUSTOMERS(CUSTOMER_ID),
     CONSTRAINT FK_msg_net
     FOREIGN KEY (NETWORK_ID)
     REFERENCES NETWORKS(NETWORK_ID)
);