INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME) values (1,'Cust_One');
INSERT INTO CUSTOMERS (CUSTOMER_ID,CUSTOMER_NAME) values (2,'Cust_Two');

INSERT INTO KEYWORDS (KEYWORD_ID,KEYWORD,CUSTOMER_ID) values (0,'Vapiano',1);
INSERT INTO KEYWORDS (KEYWORD_ID,KEYWORD,CUSTOMER_ID) values (1,'#Vapiano',1);
INSERT INTO KEYWORDS (KEYWORD_ID,KEYWORD,CUSTOMER_ID) values (2,'Wolfgangs',2);
INSERT INTO KEYWORDS (KEYWORD_ID,KEYWORD,CUSTOMER_ID) values (3,'#WOLFGANGSSTEAKH',2);
INSERT INTO KEYWORDS (KEYWORD_ID,KEYWORD,CUSTOMER_ID) values (4,'@WOLFGANGSSTEAKH',2);